version: "3.8"
services:
    container-name: product-service
    image: adoptopenjdk/openjdk8
    ports:
      - 8080:8080
    working_dir: /app
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    networks:
      - mynetwork
    volumes:

  mysql:
    container_name: mysql
    image: mysql
    ports:
      - 3306:3306
    restart: always
    networks:
      - mynetwork
    environment:
      - MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - shared-data: /var/lib/mysql

networks:
    mynetwork:
      driver: bridge
volumes:
  shared-data:
    driver_opts:
      device: /mycode/sites
      o: bind

