version: "3.8"

services:
  mysql:
    image: mysql
    ports:
      - 3306:3306
    restart: always
    networks:
      - mynetwork
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - shared-data:/var/lib/mysql

  product-service:
    ports:
      - 8080:8080
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    networks:
      - mynetwork

networks:
    mynetwork:
      driver: bridge

volumes:
  shared-data:
    driver_opts:
      device: ../mycode/demo-gRPC
      o: bind
      type: bind

